spring:
  application:
    name: shophub
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=ShopHub;encrypt=true;trustServerCertificate=true
    username: sa
    password: ShopHub@12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: BWfT+l6s0J6AH+tPvIXKerooxpSHNcKvPCuhQgfOqww=
  access-token-expiration: 20000
  refresh-token-expiration: 100000

server:
  port: 8080